{-# LANGUAGE CPP #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif
{-# LANGUAGE FlexibleInstances #-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for BNFC.
--   Generated by the BNF converter.

module BNFC.PrintLatte where

import qualified BNFC.AbsLatte
import Data.Char

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else ' ':s)

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print BNFC.AbsLatte.Ident where
  prt _ (BNFC.AbsLatte.Ident i) = doc (showString i)

instance Print BNFC.AbsLatte.Program where
  prt i e = case e of
    BNFC.AbsLatte.Program topdefs -> prPrec i 0 (concatD [prt 0 topdefs])

instance Print BNFC.AbsLatte.TopDef where
  prt i e = case e of
    BNFC.AbsLatte.TopFnDef fndef -> prPrec i 0 (concatD [prt 0 fndef])
    BNFC.AbsLatte.StrDef id inheritance memberdecls -> prPrec i 0 (concatD [doc (showString "class"), prt 0 id, prt 0 inheritance, doc (showString "{"), prt 0 memberdecls, doc (showString "}")])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print BNFC.AbsLatte.FnDef where
  prt i e = case e of
    BNFC.AbsLatte.FnDef type_ id args block -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])

instance Print BNFC.AbsLatte.Inheritance where
  prt i e = case e of
    BNFC.AbsLatte.Extends id -> prPrec i 0 (concatD [doc (showString "extends"), prt 0 id])
    BNFC.AbsLatte.NoInherit -> prPrec i 0 (concatD [])

instance Print BNFC.AbsLatte.MemberDecl where
  prt i e = case e of
    BNFC.AbsLatte.FieldDecl type_ id -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString ";")])
    BNFC.AbsLatte.MethDecl fndef -> prPrec i 0 (concatD [prt 0 fndef])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [BNFC.AbsLatte.MemberDecl] where
  prt = prtList

instance Print [BNFC.AbsLatte.TopDef] where
  prt = prtList

instance Print BNFC.AbsLatte.Arg where
  prt i e = case e of
    BNFC.AbsLatte.Arg type_ id -> prPrec i 0 (concatD [prt 0 type_, prt 0 id])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [BNFC.AbsLatte.Arg] where
  prt = prtList

instance Print BNFC.AbsLatte.Block where
  prt i e = case e of
    BNFC.AbsLatte.Block stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print [BNFC.AbsLatte.Stmt] where
  prt = prtList

instance Print BNFC.AbsLatte.Stmt where
  prt i e = case e of
    BNFC.AbsLatte.Empty -> prPrec i 0 (concatD [doc (showString ";")])
    BNFC.AbsLatte.BStmt block -> prPrec i 0 (concatD [prt 0 block])
    BNFC.AbsLatte.Decl type_ items -> prPrec i 0 (concatD [prt 0 type_, prt 0 items, doc (showString ";")])
    BNFC.AbsLatte.Ass id expr -> prPrec i 0 (concatD [prt 0 id, doc (showString "="), prt 0 expr, doc (showString ";")])
    BNFC.AbsLatte.MemAss id1 id2 expr -> prPrec i 0 (concatD [prt 0 id1, doc (showString "."), prt 0 id2, doc (showString "="), prt 0 expr, doc (showString ";")])
    BNFC.AbsLatte.Incr id -> prPrec i 0 (concatD [prt 0 id, doc (showString "++"), doc (showString ";")])
    BNFC.AbsLatte.Decr id -> prPrec i 0 (concatD [prt 0 id, doc (showString "--"), doc (showString ";")])
    BNFC.AbsLatte.Ret expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    BNFC.AbsLatte.VRet -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    BNFC.AbsLatte.Cond expr stmt -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    BNFC.AbsLatte.CondElse expr stmt1 stmt2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt1, doc (showString "else"), prt 0 stmt2])
    BNFC.AbsLatte.While expr stmt -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    BNFC.AbsLatte.StExp expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print BNFC.AbsLatte.Item where
  prt i e = case e of
    BNFC.AbsLatte.NoInit id -> prPrec i 0 (concatD [prt 0 id])
    BNFC.AbsLatte.Init id expr -> prPrec i 0 (concatD [prt 0 id, doc (showString "="), prt 0 expr])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [BNFC.AbsLatte.Item] where
  prt = prtList

instance Print BNFC.AbsLatte.Type where
  prt i e = case e of
    BNFC.AbsLatte.Int -> prPrec i 0 (concatD [doc (showString "int")])
    BNFC.AbsLatte.Str -> prPrec i 0 (concatD [doc (showString "string")])
    BNFC.AbsLatte.Bool -> prPrec i 0 (concatD [doc (showString "boolean")])
    BNFC.AbsLatte.Void -> prPrec i 0 (concatD [doc (showString "void")])
    BNFC.AbsLatte.Struct id -> prPrec i 0 (concatD [prt 0 id])
    BNFC.AbsLatte.Fun type_ types -> prPrec i 0 (concatD [prt 0 type_, doc (showString "("), prt 0 types, doc (showString ")")])
    BNFC.AbsLatte.Any -> prPrec i 0 (concatD [doc (showString "any")])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [BNFC.AbsLatte.Type] where
  prt = prtList

instance Print BNFC.AbsLatte.Expr where
  prt i e = case e of
    BNFC.AbsLatte.EVar id -> prPrec i 6 (concatD [prt 0 id])
    BNFC.AbsLatte.ELitInt n -> prPrec i 6 (concatD [prt 0 n])
    BNFC.AbsLatte.ELitTrue -> prPrec i 6 (concatD [doc (showString "true")])
    BNFC.AbsLatte.ELitFalse -> prPrec i 6 (concatD [doc (showString "false")])
    BNFC.AbsLatte.ENull -> prPrec i 6 (concatD [doc (showString "null")])
    BNFC.AbsLatte.ENew id -> prPrec i 6 (concatD [doc (showString "new"), prt 0 id])
    BNFC.AbsLatte.EApp id exprs -> prPrec i 6 (concatD [prt 0 id, doc (showString "("), prt 0 exprs, doc (showString ")")])
    BNFC.AbsLatte.EString str -> prPrec i 6 (concatD [prt 0 str])
    BNFC.AbsLatte.ECast id -> prPrec i 6 (concatD [doc (showString "("), prt 0 id, doc (showString ")null")])
    BNFC.AbsLatte.EAcc id1 id2 -> prPrec i 6 (concatD [prt 0 id1, doc (showString "."), prt 0 id2])
    BNFC.AbsLatte.EMeth id1 id2 exprs -> prPrec i 6 (concatD [prt 0 id1, doc (showString "."), prt 0 id2, doc (showString "("), prt 0 exprs, doc (showString ")")])
    BNFC.AbsLatte.Neg expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    BNFC.AbsLatte.Not expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    BNFC.AbsLatte.EMul expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    BNFC.AbsLatte.EAdd expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    BNFC.AbsLatte.ERel expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    BNFC.AbsLatte.EAnd expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    BNFC.AbsLatte.EOr expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [BNFC.AbsLatte.Expr] where
  prt = prtList

instance Print BNFC.AbsLatte.AddOp where
  prt i e = case e of
    BNFC.AbsLatte.Plus -> prPrec i 0 (concatD [doc (showString "+")])
    BNFC.AbsLatte.Minus -> prPrec i 0 (concatD [doc (showString "-")])

instance Print BNFC.AbsLatte.MulOp where
  prt i e = case e of
    BNFC.AbsLatte.Times -> prPrec i 0 (concatD [doc (showString "*")])
    BNFC.AbsLatte.Div -> prPrec i 0 (concatD [doc (showString "/")])
    BNFC.AbsLatte.Mod -> prPrec i 0 (concatD [doc (showString "%")])

instance Print BNFC.AbsLatte.RelOp where
  prt i e = case e of
    BNFC.AbsLatte.LTH -> prPrec i 0 (concatD [doc (showString "<")])
    BNFC.AbsLatte.LE -> prPrec i 0 (concatD [doc (showString "<=")])
    BNFC.AbsLatte.GTH -> prPrec i 0 (concatD [doc (showString ">")])
    BNFC.AbsLatte.GE -> prPrec i 0 (concatD [doc (showString ">=")])
    BNFC.AbsLatte.EQU -> prPrec i 0 (concatD [doc (showString "==")])
    BNFC.AbsLatte.NE -> prPrec i 0 (concatD [doc (showString "!=")])

